name: Sync crates to index

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout crate storage
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Check out crate index
        uses: actions/checkout@v2
        with:
          repository: cschlosser/crate-index
          path: .crate-index
          ref: master
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            default: true

      - name: Install cargo-index
        run: cargo install cargo-index

      - name: Update index
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" &&
          ./update.sh ./.crate-index
